"""adds Scooter Rental one to many

Revision ID: 77aa8c342ada
Revises: 4148c22968c3
Create Date: 2024-04-01 14:49:38.931789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77aa8c342ada'
down_revision = '4148c22968c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scooter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'scooter', ['scooter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('scooter_id')

    # ### end Alembic commands ###
