"""add nullable=False

Revision ID: b5dd1328dd12
Revises: 6ffdbf6705d9
Create Date: 2024-04-02 01:27:39.729545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5dd1328dd12'
down_revision = '6ffdbf6705d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.alter_column('is_returned',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.alter_column('is_returned',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
