"""adds Customer email

Revision ID: dc977e39e61f
Revises: 1b018ffd0599
Create Date: 2024-04-01 14:32:01.747893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc977e39e61f'
down_revision = '1b018ffd0599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
