"""adds Scooter model

Revision ID: f5fc8fdd4ed4
Revises: 9f0c2b8cddff
Create Date: 2024-04-01 14:05:54.981007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5fc8fdd4ed4'
down_revision = '9f0c2b8cddff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scooter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('charge_percent', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scooter')
    # ### end Alembic commands ###
